---
jobs:

- name: create_db_bu-AUDITING
  public: true
  plan:
  - get: alpine_image
  - get: postgres-scripts-src
  - task: create_db_bu-AUDITING
    image: alpine_image
    privileged: true
    config:
      platform: linux
      inputs:
      - name: postgres-scripts-src
      params:
        PGPASSWORD: ((test_postgres_pwd))
      run:
        path: sh
        args:
          - "-ec"
          - |

            BASE=`pwd`

            mkdir abort_dir
            echo "This was aborted" > abort_dir/slack_abort.txt

            # Steps to make a Baseline
            echo
            echo "  CONFIGURE PSQL"
            echo
            apk add postgresql-client > /dev/null 2>&1

            echo
            echo "  DEFINE NECESSARY STEPS"
            echo
            export BU_CREATION_STEPS_FILE="${BASE}/postgres-scripts-src/night_tests/postgresql/auditing/bu_db_b4_nighttest.auditing.sql"

            echo
            echo "  CREATE DB BU BEFORE NIGHT TESTS RUNNING"
            echo


            export DB_TO_RECREATE="xbsdb"
            export DB_B4_LATEST_TEST_RUN="${DB_TO_RECREATE}_b4_latest_nighttest_run"
            export DB_B4_LATEST_TEST_RUN_OLD="${DB_TO_RECREATE}_b4_latest_nighttest_run_old"
            export DB_B4_LATEST_TEST_RUN_OLDEST="${DB_TO_RECREATE}_b4_latest_nighttest_run_oldest"

            psql -h postgres-definitely-careful-muskox.clo9rzixjmo4.eu-west-1.rds.amazonaws.com -p 5432 -d postgres -U postgres_user -f ${BU_CREATION_STEPS_FILE}



- name: rollback_db-AUDITING
  public: true
  plan:
  - get: alpine_image
  - get: postgres-scripts-src
  - task: rollback_db-AUDITING
    image: alpine_image
    privileged: true
    config:
      platform: linux
      inputs:
      - name: postgres-scripts-src
      params:
        PGPASSWORD: ((test_postgres_pwd))
      run:
        path: sh
        args:
          - "-ec"
          - |

            BASE=`pwd`

            # Steps to make a Baseline
            echo
            echo "  CONFIGURE PSQL"
            echo
            apk add postgresql-client > /dev/null 2>&1

            echo
            echo "  DEFINE NECESSARY STEPS"
            echo
            export DBRECREATION_STEPS_FILE="${BASE}/postgres-scripts-src/night_tests/postgresql/auditing/rollback_db_aft_nighttest.auditing.sql"

            echo
            echo "  ROLLBACK DB TO THE STATE BEFORE NIGHT TESTS RUNNING"
            echo


            export DB_TO_RECREATE="xbsdb"
            export DB_B4_LATEST_TEST_RUN="${DB_TO_RECREATE}_b4_latest_nighttest_run"

            psql -h postgres-definitely-careful-muskox.clo9rzixjmo4.eu-west-1.rds.amazonaws.com -p 5432 -d postgres -U postgres_user -f ${DBRECREATION_STEPS_FILE}

    on_abort:
          do:
            - get: postgres-scripts-src_ensuring
            - task: rollback_db-AUDITING_ensuring
              image: alpine_image
              privileged: true
              config:
                platform: linux
                inputs:
                - name: postgres-scripts-src_ensuring
                params:
                  PGPASSWORD: ((test_postgres_pwd))
                run:
                  path: sh
                  args:
                    - "-ec"
                    - |

                      BASE=`pwd`

                      # Steps to make a Baseline
                      echo
                      echo "  CONFIGURE PSQL"
                      echo
                      apk add postgresql-client > /dev/null 2>&1

                      echo
                      echo "  DEFINE NECESSARY STEPS"
                      echo
                      export DBRECREATION_STEPS_FILE="${BASE}/postgres-scripts-src_ensuring/night_tests/postgresql/auditing/rollback_db_aft_nighttest.auditing.sql"

                      echo
                      echo "  ROLLBACK DB TO THE STATE BEFORE NIGHT TESTS RUNNING"
                      echo


                      export DB_TO_RECREATE="xbsdb"
                      export DB_B4_LATEST_TEST_RUN="${DB_TO_RECREATE}_b4_latest_nighttest_run"

                      psql -h postgres-definitely-careful-muskox.clo9rzixjmo4.eu-west-1.rds.amazonaws.com -p 5432 -d postgres -U postgres_user -f ${DBRECREATION_STEPS_FILE}

resources:

- name: alpine_image
  type: docker-image
  source:
    repository: alpine
    tag: latest

- name: postgres-scripts-src
  type: git
  source:
    uri: git@github.com:90poe/e2e-tests-infra.git
    branch: DEVOPS-837_audit_db_recreation
    private_key: ((asdf))

- name: postgres-scripts-src_ensuring
  type: git
  source:
    uri: git@github.com:90poe/e2e-tests-infra.git
    branch: DEVOPS-837_audit_db_recreation
    private_key: ((asdf))

